create TABLE groups (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR (200) NOT NULL,
  parent_id BIGINT,
  user_detail_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE passmanager (
  id BIGSERIAL PRIMARY KEY,
  user_detail_id BIGINT NOT NULL,
  group_id BIGINT NOT NULL,
  name VARCHAR (200) NOT NULL,
  login VARCHAR (200) NOT NULL,
  credentials TEXT NOT NULL,
  url TEXT NOT NULL,
  pass_type VARCHAR(200)NOT NULL,
  notes TEXT,
  created_at TIMESTAMP NOT NULL
);


ALTER TABLE groups
  ADD CONSTRAINT GROUPS_USER_DETIAL_FK FOREIGN KEY (user_detail_id) REFERENCES user_details(id);

ALTER TABLE groups
  ADD CONSTRAINT GROUPS_GROUP_PARENT_ID_FK FOREIGN KEY (parent_id) REFERENCES groups(id);

ALTER TABLE passmanager
  ADD CONSTRAINT PASSMANAGER_GROUPS_FK FOREIGN KEY (group_id) REFERENCES groups(id);


ALTER TABLE passmanager
  ADD CONSTRAINT PASSMANAGER_USER_DETAIL_FK FOREIGN KEY (user_detail_id) REFERENCES user_details(id);


